### ISSUE TITLE
离线版本内容不全

### ISSUE THREAD

**Issue by zodiacg** [Unknwon/the-way-to-go_ZH_CN#118]
只有第3章和第10章内容是完整的，之间的大部分都只有章节的X.0那一页的内容，之后就跳到下一章了

**Comment by Unknwon** [comment]
我完全不懂你在说什么。。哪里有离线版本？

**Comment by zodiacg** [comment]
http://wiki.jikexueyuan.com/project/the-way-to-go/

**Comment by Unknwon** [comment]
。。。这个应该反馈给极客学院。。

**Comment by Unknwon** [comment]
cc @vincent4j

**Comment by tl3shi** [comment]
我fork了一份，改了下，放到gitbook上了.  特此过来 @ 以下 @Unknwon ，gitbook上线上阅读效果更好，线下也有其他如pdf等格式~ 然而 gitbook生产的pdf 图片有问题 不知道怎么解决更好。
通过[gitbook](http://go.tanglei.name)可以访问或者下载。

**Comment by Unknwon** [comment]
@tl3shi 多谢、。不过同步是个麻烦事

**Comment by tl3shi** [comment]
@Unknwon   我每隔几天就过来merge 一下~  :)

**Comment by Inza9hi** [comment]
@tl3shi 赞~

**Comment by qiansen1386** [comment]
@Inza9hi https://www.gitbook.com/book/tl3shi/the-way-to-go/details Check this out!:wink:

**Comment by meteormatt** [comment]
`gitbook的pdf 图片问题`解决了吗？
