### ISSUE TITLE
bug: code list overflow in chapter 4.5.2.1

### ISSUE THREAD

**Issue by selaselah** [Unknwon/the-way-to-go_ZH_CN#127]
this code list:

>func IntFromFloat64(x float64) int {
>    if math.MinInt32 <= x && x <= math.MaxInt32 { // x lies in the integer range
>        whole, fraction := math.Modf(x)
>        if fraction >= 0.5 {
>            whole++
>        }
>        return int(whole)
>    }
>    panic(fmt.Sprintf("%g is out of the int32 range", x))
>}

if x > int32max + 0.5 the result will overflow

**Comment by Unknwon** [comment]
不是很懂你给的情况，什么情况下会在 ` x > int32max` 的情况下 `+0.5`？

**Comment by selaselah** [comment]
sorry, i made a mistake:(

**Comment by Unknwon** [comment]
:smiley:
