### ISSUE TITLE
”百度+思考+失败+翻墙+谷歌+尝试=解决“等式不成立

### ISSUE THREAD

**Issue by TurnOffNOD** [Unknwon/the-way-to-go_ZH_CN#128]
”符合等式 百度+思考+失败+翻墙+谷歌+尝试=解决 的问题最好不要发问“

”百度+思考+失败+翻墙+谷歌+尝试=解决“这个等式不成立

往往baidu了之后，下载的golang安装包是baidu插入恶意代码的，安装时出现全家桶，电脑死机，或者说是写什么代码都被删，而且全家桶还没法卸载；

或者搜索问题时候出现一大推垃圾信息，新人什么也不知道，也不知道对不对，照着做搞得彻底乱了，最后放弃。

应该把baidu去掉，换成”翻墙google(.hk)+思考+失败+翻墙+google/ncr+尝试=解决“

**Comment by Unknwon** [comment]
这句话的限定非常完备：

`符合等式 百度+思考+失败+翻墙+谷歌+尝试=解决 `

你所描述的情况就是不符合这个等式，也就是可以发问。

**Comment by zouyx** [comment]
我觉得百度和谷歌都只是一个代名词，代表的是上网搜索答案，不管从哪里，所以无需纠结，其实我觉得应该加上http://stackoverflow.com 
百度+思考+失败+翻墙+谷歌+尝试+stackflow=解决

**Comment by jhfnetboy** [comment]
同意楼上
