### ISSUE TITLE
10.1章节有错误是｛｝不是()

### ISSUE THREAD

**Issue by freeddser** [Unknwon/the-way-to-go_ZH_CN#130]
And here are some initializations:
inter := Interval{0,3} (A) inter2 := Interval{end:5, start:1} (B) inter3 := Interval{end:5} (C)
是{}不是()
intr := Interval(0, 3)            (A)
intr := Interval(end:5, start:1)  (B)
intr := Interval(end:5)           (C)

**Comment by Unknwon** [comment]
多谢指正！已修复。

**Comment by freeddser** [comment]
请问一下，你们后续章节还翻译吗，最近一直没见你们更新。。

**Comment by Unknwon** [comment]
目前时间不是很多。。
