### ISSUE TITLE
4.6 字符串 节 勘误

### ISSUE THREAD

**Issue by skiy** [Unknwon/the-way-to-go_ZH_CN#148]
- 第 i 个字节：`str[i]`   
应该改为
- 第 i 个字节：`str[i - 1]`   
https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/04.6.md   第34行~

**Comment by Unknwon** [comment]
:trollface: 这位仁兄有没有兴趣来个 PR

**Comment by skiy** [comment]
好~已PR~
