### ISSUE TITLE
关于9.5章中的问题

### ISSUE THREAD

**Issue by zouyx** [Unknwon/the-way-to-go_ZH_CN#174]
当前目录下（examples/chapter9）有一个名为 package_test.go 的程序, 它使用了自定义包 pack1 中 pack1.go 的代码。这段程序(联通编译链接生成的 pack1.a)存放在当前目录下一个名为 pack1 的文件夹下。所以链接器将包的对象和主程序对象链接在一起。

链接如下：https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/09.5.md

我觉得有点问题，上面提到联通编译器是怎么编译？如果没有他提到的编译过的代码，下面的代码是不能运行成功的。

我只能是使用以下代码运行成功，请帮忙解答下谢谢。

```go
 1 package main
  2
  3 import (
  4     "fmt"
  5     "./pack1"
  6 )
  7 func main() {
  8     var test1 string
  9     test1 = pack1.ReturnStr()
 10     fmt.Println("str:",test1)
 11     fmt.Println("int:",pack1.Pack1Int)
 12 }
```

**Comment by Unknwon** [comment]
> 如果没有他提到的编译过的代码，下面的代码是不能运行成功的。

你这句话歧义有点多。。能不能改进一下描述。。

**Comment by zouyx** [comment]
就是我不明白文中提到的：联通编译链接生成的 pack1.a 是什么意思

**Comment by Unknwon** [comment]
.a 格式吗？这是go的非main包编译链接后的存在形式

**Comment by ArkBriar** [comment]
原文是"together with its compiled-and-linked archived form pack1.a"
显然是译者笔误，“连同”写作了“联通” @zouyx @Unknwon 

稍微补充下
+ .a是linux下的静态库
+ go的非main包都需要编译成静态库(并和源代码一起存放在 $GOPATH 下)才能和标准库一样使用，否则就要在import的时候标识路径
+ 尽量不要把 GOPATH 和 GOROOT 设为同一个，golang提供两个环境变量就是为了防止污染核心库

拙见见笑

**Comment by Unknwon** [comment]
@ArkBriar typo已修复 :smile:

**Comment by zouyx** [comment]
谢谢两位大神的关注！:smirk:

**Comment by Unknwon** [comment]
:trollface:
