### ISSUE TITLE
对作者的无私奉献表示在感谢！

### ISSUE THREAD

**Issue by toyang** [Unknwon/the-way-to-go_ZH_CN#192]
另个想问个问题，GO的容器是不是太少了？对比java，什么hashset  linkedhashset等等一大堆，GO在这方面就逊色多了，应该说对于google的大神来说写个这些容器不算难事，官方难道没有考虑在标准库里面加入吗？

**Comment by Unknwon** [comment]
容器是个什么东西。。？

多谢支持！

**Comment by toyang** [comment]
抱歉，概念说的可能有点混淆了，我是指对应的java集合框架，C++里叫容器，GO在这方面有计划加强吗，下个版本会增加吗？现在貌似只有slice相当 于arraylist

**Comment by Unknwon** [comment]
@toyang 目前go只有这些吧。。https://gowalker.org/container

**Comment by toyang** [comment]
那个GO下个版本的开发计划在哪里查看呢？

**Comment by Unknwon** [comment]
https://github.com/golang/go/wiki/DesignDocuments
