### ISSUE TITLE
14.6 文章下的链接404

### ISSUE THREAD

**Issue by mutouzhang** [Unknwon/the-way-to-go_ZH_CN#207]
**感谢无闻大大的翻译 这个位置的链接失效了**

#**14.6 协程和恢复（recover）**
**.....**

** 链接 **

目录

上一节：通道，超时和计时器 

下一节：对比新旧模型：任务和工作 <-------------点击后404

**Comment by Unknwon** [comment]
噢。。。这还没翻译呢。。不是失效了

**Comment by SunnyShao** [comment]
无闻大大，什么时候翻译这段，我们期待着

**Comment by Unknwon** [comment]
现在比较忙。。
