### ISSUE TITLE
不能简单地认为每一个 const 关键字，iota 就重置为 0 吧

### ISSUE THREAD

**Issue by bohanyang** [Unknwon/the-way-to-go_ZH_CN#209]
package main

    import (
	    "fmt"
    )
    
    const (
	    a = iota     // iota = 0, a = 0
	    b            // iota = 1, b = iota, b = 1
	    c = iota + 1 // iota = 2, c = iota + 1 = 2 + 1 = 3
	    d            // iota = 3, d = iota + 1 = 3 + 1 = 4
	    e = iota     // iota = 4, e = 4
    )
    
    const f, g = iota, iota // iota = 0, 0; f, g = 0, 0
    
    const (
        h, i = iota, iota + 1
        j, k
    )

    func main() {
	    fmt.Println(a)
	    fmt.Println(b)
	    fmt.Println(c)
	    fmt.Println(d)
	    fmt.Println(e)
	    fmt.Println(f)
	    fmt.Println(g)
	    fmt.Println(h)
	    fmt.Println(i)
	    fmt.Println(j)
	    fmt.Println(k)
    }

Output:
 - 0                                                                                                                                                                                            
 - 1                                                                                                                                                                                            
 - 3                                                                                                                                                                                            
 - 4                                                                                                                                                                                            
 - 4                                                                                                                                                                                            
 - 0                                                                                                                                                                                            
 - 0                                                                                                                                                                                            
 - 0                                                                                                                                                                                            
 - 1                                                                                                                                                                                            
 - 1                                                                                                                                                                                            
 - 2

**Comment by Unknwon** [comment]
论点所对应的内容是。。。？
