### ISSUE TITLE
“13.1 错误处理” 章节部分问题

### ISSUE THREAD

**Issue by wutaizeng** [Unknwon/the-way-to-go_ZH_CN#211]
1. PathError 实现方法 String, 应该是实现方法 Error。原书也写的实现方法 String, 查看 go 源代码实现的是方法 Error
2. SyntaxError 问题同上
3. net.Errot 拼写错误，应该是 net.Error

**Comment by Unknwon** [comment]
hi，您可以提交 PR。。
