### ISSUE TITLE
示例 6.5 minmax.go的代码没有涉及到空白符

### ISSUE THREAD

**Issue by lwhhhh** [Unknwon/the-way-to-go_ZH_CN#253]

**Comment by appleboy** [comment]
看不太懂你的意思

**Comment by lwhhhh** [comment]
@appleboy  https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/06.2.md#623-空白符blank-identifier 这一段在讲空白符的使用，可是6.5 minmax.go的代码好像就返回从小到大的两个数，没有涉及到空白符的内容

**Comment by Unknwon** [comment]
好像是没讲到。。但是原著中放了。。额。
