### ISSUE TITLE
是否有必要固定 git 的 line endings 

### ISSUE THREAD

**Issue by songjiayang** [Unknwon/the-way-to-go_ZH_CN#258]
在提交 这个 [pr](https://github.com/Unknwon/the-way-to-go_ZH_CN/pull/256) 的时候发现 `09.11.md` 文件默认换行符是 `\r\n`  ，查询历史记录，发现是在这次 [commit](https://github.com/Unknwon/the-way-to-go_ZH_CN/commit/a7cc4c395edaf64e54c78ed598d024c6db1ae024#diff-99b1e7b5d5c06a0da4c28baca4f6ef21) 被修改了的。

排查了所有文件，发现使用 `\n` 占多数，那么是否有必要统一配置项目文件换行符为 `\n` 呢？

具体配置请参考链接： https://help.github.com/articles/dealing-with-line-endings/

建议将统一配置放到  .gitattributes 文件.

cc @appleboy

**Comment by appleboy** [comment]
Nice idea.

**Comment by songjiayang** [comment]
需要确认下统一使用 `crlf` 还是 `lf`

**Comment by Unknwon** [comment]
建议使用 unix 格式的 line ending.
