### ISSUE TITLE
4.8的例子为何格式化以后时间都变了

### ISSUE THREAD

**Issue by lyb124553153** [Unknwon/the-way-to-go_ZH_CN#259]
包中的一个预定义函数 func (t Time) Format(layout string) string 可以根据一个格式化字符串来将一个时间 t 转换为相应格式的字符串，你可以使用一些预定义的格式，如：time.ANSIC 或 time.RFC822。

一般的格式化设计是通过对于一个标准时间的格式化描述来展现的，这听起来很奇怪，但看下面这个例子你就会一目了然
`fmt.Println(t.Format("02 Jan 2006 15:04"))`

输出：
21 Jul 2011 10:31

**Comment by Unknwon** [comment]
格式化字符串只是格式化字符而已，和真实实现没有任何关系。
