### ISSUE TITLE
项目接入gitbook的可能性

### ISSUE THREAD

**Issue by apt-getyou** [Unknwon/the-way-to-go_ZH_CN#261]
目前我阅读这本书的方式还是在github网站上直接阅读，或者clone到本地后使用markdown软件阅读。

我也不知道这个项目是否有加入类似于gitbook的插件。

但我还是希望能够有一个ebook导出功能，方便导出mobi等格式，让我们能在kindle等设备上阅读

**Comment by apt-getyou** [comment]
如果已经有导出功能，希望能在README.md内指出

**Comment by Unknwon** [comment]
导出并不是一件容易的事情。。你可以在 http://wiki.jikexueyuan.com/project/the-way-to-go/ 上看

**Comment by SmallFatCYW** [comment]
@Unknwon  然而极客学院对手机的支持并不好啊。。。没有自适应就算了，那侧边栏特别烦人。。。还不如在github上看233333(我有些时候用手机看教程用电脑码，因为喜欢全屏编辑器。。。)

**Comment by Unknwon** [comment]
你的需求可以用双屏幕解决。。

**Comment by meteormatt** [comment]
**SUMMARY.md**改改要吐血。还是GitHub上看看吧。
