### ISSUE TITLE
10.6章节的文字错误

### ISSUE THREAD

**Issue by lyb124553153** [Unknwon/the-way-to-go_ZH_CN#263]
练习 10.9 point_methods.go：

从 point.go 开始（第 10.1 节的****联系****）：使用方法来实现 Abs() 和 Scale()函数，Point 作为方法的接收者类型。也为 Point3 和 Polar 实现 Abs() 方法。完成了 point.go 中同样的事情，只是这次通过方法。

从 point.go 开始（第 10.1 节的练习）

**Comment by Unknwon** [comment]
感谢指出！建议提交一个 PR 修复 :trollface:
