### ISSUE TITLE
关于10.6.1章节中关于方法接受者的一句说明

### ISSUE THREAD

**Issue by xiaowing** [Unknwon/the-way-to-go_ZH_CN#265]
最近在用《The Way to Go》的中文版学习golang(很棒的翻译，赞！)，想请教一下10.6.1章中的下述描述想表达什么意思? 看起来有点暧昧：

> 最后接收者不能是一个指针类型，但是它可以是任何其他允许类型的指针。

我查阅了一下英文原版，似乎也是比较语焉不详。

> Lastly it cannot be a pointer type, but it can be a pointer to any of the allowed types.

我一开始的理解是 “定义方法时，接受者类型不能是一个指针”。但是我简单写了一段代码尝试了一下，发现似乎又不是这么一回事:

我写的测试代码如下：

```go
package main

import (
	"fmt"
	"strconv"
)

type Person struct {
	id   string
	name string
	age  int
}

func (this *Person) ToString() string {
	result := this.id + " " + this.name + " " + strconv.Itoa(this.age)
	return result
}

func main() {
	foo := &Person{"BE001", "John Lennon", 38}
	fmt.Printf("ToString() : %s\n", foo.ToString())
}
```

希望和大家讨论一下，这句话写在这里到底是想提醒读者注意什么，谢谢。

**Comment by Unknwon** [comment]
是有点迷惑。。要不干脆发个 PR 把这句删了吧。。

**Comment by lyb124553153** [comment]
不能是指针类型，但可以是某个类型的指针。如果用指针做接收者类型，那么这个方法会直接操作接受者的某个属性的值。
用指针类型作接收者的意思是如果你定义一个指针类型，那么不能在指针类型上面定义方法
`

package main

import (
	"fmt"
	"strconv"
)

type Person int

type wrongrec *Person

func (this ll) ToString() string {
	result := strconv.Itoa(Person)
	return result
}
`

**Comment by xiaowing** [comment]
感谢@lyb124553153 ，你的例子很清晰易懂。尝试了一下，编译器对于这种情况直接报错：

> invalid receiver type wrongrec (wrongrec is a pointer type)

这下我明白了，就是说方法可以绑定到一个结构体类型，也可以是一个结构体的指针，但是如果一个数据类型本身就被声明为是一个指针类型，则无法绑定方法。

疑惑解决，本Issue关闭～
