### ISSUE TITLE
12.9 json中的例子

### ISSUE THREAD

**Issue by freeddser** [Unknwon/the-way-to-go_ZH_CN#271]
file, _ := os.OpenFile("vcard.json", os.O_CREATE|os.O_WRONLY, 0) 
这个0生成一个没权限的文件？原书就是错的吧？

**Comment by Unknwon** [comment]
有道理。。发个 PR 修复下 :laughing:

**Comment by lynn9388** [comment]
#349 中已修复@Unknwon，建议关闭。
