### ISSUE TITLE
[07.1] fibonacci_array.go 我这么做是正确的吗？

### ISSUE THREAD

**Issue by wozzup** [Unknwon/the-way-to-go_ZH_CN#278]
https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/07.1.md
练习7.3：fibonacci_array.go: 
在第 6.6 节我们看到了一个递归计算 Fibonacci 数值的方法。
但是通过数组我们可以更快的计算出 Fibonacci 数。
完成该方法并打印出前 50 个 Fibonacci 数字。

```go
package main

import (
    "fmt"
)

func fibonacci(n [10]int) int {
    a, b := 0, 1
    for k, _ := range n {
        a, b = b, a + b
        fmt.Printf("fibonacci(%d) = %d\n", k, a)
    }

    return a
}

func main() {
    var n [10]int
    fibonacci(n)
}
```
我这么做是正确的吗？

**Comment by Unknwon** [comment]
额。。这里不负责回答问题，你可以去相关论坛提问。
