### ISSUE TITLE
提供的极客学院文档中图片 404 了

### ISSUE THREAD

**Issue by alphatr** [Unknwon/the-way-to-go_ZH_CN#282]
如题

<img width="957" src="https://cloud.githubusercontent.com/assets/1798972/18236847/3b233c66-735d-11e6-9104-1f9ebf07016b.png">

**Comment by Unknwon** [comment]
。。这个我控制不了，我必须首先保证github能正常浏览。。你应该给极客学院提交bug。。:trollface:
