### ISSUE TITLE
7.2章 示例 7.8 make_slice.go的输出结果缺少一行”\n“结果

### ISSUE THREAD

**Issue by LockMo** [Unknwon/the-way-to-go_ZH_CN#288]
Slice at 0 is 0  
Slice at 1 is 5  
Slice at 2 is 10  
Slice at 3 is 15  
Slice at 4 is 20  
Slice at 5 is 25  
Slice at 6 is 30  
Slice at 7 is 35  
Slice at 8 is 40  
Slice at 9 is 45

The length of slice1 is 10  
The capacity of slice1 is 10

**Comment by Unknwon** [comment]
建议直接提交 PR，多谢！
