### ISSUE TITLE
5.3 switch 是否有表达问题？

### ISSUE THREAD

**Issue by hitdavid** [Unknwon/the-way-to-go_ZH_CN#309]
问题纯属猜测哈，
记得以前学习C，switch对比多重if-else-if的性能优势是比较明显的，
switch会生成跳表，时间复杂度O(1)，
在5.3中有如下表述：
> 每一个 case 分支都是唯一的，从上至下逐一测试，直到匹配为止。
不知道是否有问题。

**Comment by Unknwon** [comment]
有什么问题。。？

**Comment by hitdavid** [comment]
初学者哈，纯属猜测哈，不对的地方见谅
每一个case分支都是从上到下逐一测试，直到匹配为止的吗？
如果这样的话，那么golang的switch与多重if-else-if的性能一致？
没有任何编译优化？

**Comment by hitdavid** [comment]
对于大多数语言，switch的时间复杂度可以认为是是O(1)，而多重if-else-if的时间复杂度是O(n)。

**Comment by Unknwon** [comment]
讲道理。。语言内部细节我不懂。。你可以去看 https://github.com/qyuhen/book 有相关的源码分析。。

**Comment by hitdavid** [comment]
昨晚求证了一下，去Golang-China发了个帖子问问，看见回复如下：

> minux <minux@golang.org>
> 0:08 (11小时前)
> 
>
> > 发送至 Golang-China 
> > On Feb 1, 2017 10:34 AM, "杜宇" <hitdavid@gmail.com> wrote:
> > 记得以前学习C，switch对比多重if-else-if的性能优势是比较明显的，
> > switch会生成跳表，时间复杂度近似O(1)。
> > golang有这种优化吗？
> > 或者说如果使用golang写一段常亮比较switch-case，是否有优化？
> 
> gc 使用二分搜索实现 switch，不是跳转表。
> 不过对于很紧凑的整数 switch，没准以后会用跳转表（目前没用是因为后端不支持声明跳转表），我记得有个 issue 是关于这个的。

所以看来，即使是二分查找，也不必每个case自上而下逐个测试的。
回头我试试提交个修改：）

**Comment by Unknwon** [comment]
:trollface: 学习了。。
