### ISSUE TITLE
exercises/chapter_12/calculator.go  代码可能存在的问题

### ISSUE THREAD

**Issue by Instrye** [Unknwon/the-way-to-go_ZH_CN#312]
配合 chapter_11/stack/stack_general.go
尝试运行代码时,出现两点问题
q1: Stack.Pop() 返回值为两个 代码中只处理一个返回值会出现 
`multiple-value calc1.Pop() in single-value context `
提示,更改赋值过程为
`q, _ := calc1.Pop()
p, _ := calc1.Pop()`
解决
q2:利用q,p值做算术运算时,会出现
`invalid operation: p + q (operator + not defined on interface)`
改代码为
`p.(int)+q.(int)`
可以解决，
请问这是我个人电脑问题还是代码确实存在问题,除了`p.(int)+q.(int)`还有更好的解决办法吗？
感谢。

**Comment by Unknwon** [comment]
恩。。有道理，书本的代码有些事过时了，最好能发个 PR 过来修复下 :trollface:

>请问这是我个人电脑问题还是代码确实存在问题,除了p.(int)+q.(int)还有更好的解决办法吗？

目测没有。。除非定义类型的时候就不要用接口，用具体类型 int 之类的
