### ISSUE TITLE
10.7 类型的 String() 方法和格式化描述符  fmt.Print()应为fmt.Printf()

### ISSUE THREAD

**Issue by vfbear** [Unknwon/the-way-to-go_ZH_CN#358]
还有 fmt.Print() 和 fmt.Println() 也会自动使用 String() 方法。

fmt.Print()应为fmt.Printf()

**Comment by Unknwon** [comment]
建议提交个 PR 吧？嘿嘿。。

**Comment by lynn9388** [comment]
根据[官方文档](https://golang.org/pkg/fmt/#Stringer)

> Stringer is implemented by any value that has a String method, which defines the “native” format for that value. The String method is used to print values passed as an operand to any format that accepts a string or to an unformatted printer such as Print.

可知该描述没错，建议@Unknwon关闭
