### ISSUE TITLE
11.1章 接口

### ISSUE THREAD

**Issue by dcb1** [Unknwon/the-way-to-go_ZH_CN#361]
示例11.1下面有这样一段话
“如果 Shaper 有另外一个方法 Perimeter()，但是Square 没有实现它，即使没有人在 Square 实例上调用这个方法，编译器也会给出上面同样的错误。“

实验结果是： 如果用示例11.1的代码采用最短的初始化和赋值 即 areaIntf := sq1，并不会触发上面说的错误

**Comment by Unknwon** [comment]
。。给个链接吧。。我都不知道你在说神马。。

**Comment by dcb1** [comment]
https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/11.1.md

**Comment by dcb1** [comment]
https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/11.1.md

中间一示例代码 
package main

import "fmt"

type Shaper interface {
	Area() float32
        Permiteter() float32  //*****这里添加了一个抽象方法
}

type Square struct {
	side float32
}

func (sq *Square) Area() float32 {
	return sq.side * sq.side
}

func main() {
	sq1 := new(Square)
	sq1.side = 5

	// var areaIntf Shaper
	// areaIntf = sq1
	// shorter,without separate declaration:
	// areaIntf := Shaper(sq1)
	// or even:
	areaIntf := sq1
	fmt.Printf("The square has area: %f\n", areaIntf.Area())
}

例子下面有段话
“如果 Shaper 有另外一个方法 Perimeter()，但是Square 没有实现它，即使没有人在 Square 实例上调用这个方法，编译器也会给出上面同样的错误。”

如果是运行上述代码 并不会报错

**Comment by Unknwon** [comment]
恩。。给的例子确实有点让新手懵逼，我修改了下现在代码和描述正确了
