### ISSUE TITLE
14.3 channel 的非阻塞发送

### ISSUE THREAD

**Issue by oxbambooxo** [Unknwon/the-way-to-go_ZH_CN#364]
14.3 中提到

可以通过 _ = ch <- v 来实现非阻塞发送，因为空标识符获取到了发送给 ch 的任何东西。在示例程序 14.2 中使用这些可以改进为版本 goroutine3.go，输出相同。

但是在实际运行时得到编译时错误

syntax error: unexpected <- at end of statement

**Comment by Unknwon** [comment]
说话的时候给个链接吧。。

**Comment by oxbambooxo** [comment]
因为没有锚记，所以还是需要搜索下文本才能找到出处：

https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/14.3.md
可以通过 _ = ch <- v 来实现非阻塞发送，因为空标识符获取到了发送给 ch 的任何东西。在示例程序 14.2 中使用这些可以改进为版本 goroutine3.go，输出相同。

**Comment by Unknwon** [comment]
具体哪一行出现了你说的错误？

**Comment by oxbambooxo** [comment]
在文件中的第40行提到的，按照提示直接这么写的话会出现编译错误：

```
func main() {
	ch := make(chan float64)
	defer close(ch)

	v := 123
	_ = ch <- v
}
```

只是奇怪为什么会见到一个官网上没介绍过的语法，新特性？

**Comment by Unknwon** [comment]
恩确实。。我把这句话删了吧。
