### ISSUE TITLE
14.6 协程和恢复（recover） defer处少一个括号

### ISSUE THREAD

**Issue by li744831579** [Unknwon/the-way-to-go_ZH_CN#406]
`func safelyDo(work *Work) {
    defer func() {
        if err := recover(); err != nil {
            log.Printf("Work failed with %s in %v", err, work)
        }
    }()`

**Comment by li744831579** [comment]
14.6 协程和恢复（recover） defer处少一个括号

**Comment by Unknwon** [comment]
额。。建议提交一个 Pull Request 修复一下。。嘿嘿

**Comment by suizhiyuan** [comment]
表示你们这个效率  低的过分。

**Comment by Unknwon** [comment]
根本就没有效率。。什么叫低的过分 :joy:
