### ISSUE TITLE
14章目录编辑错误

### ISSUE THREAD

**Issue by onloadcc** [Unknwon/the-way-to-go_ZH_CN#408]
14章 目录中只有到 14.6 协程和恢复（recover）
进去点击可以到 [14.9 实现 Futures 模式](https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/14.9.md)， 但是点击 下一节 [复用](https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/14.10.md)  链接无效。

**Comment by Unknwon** [comment]
对的。。因为没翻译出来还。。
