### ISSUE TITLE
关于函数类型声明

### ISSUE THREAD

**Issue by dongshimou** [Unknwon/the-way-to-go_ZH_CN#418]
> 函数也可以以申明的方式被使用，作为一个函数类型，就像：

> type binOp func(int, int) int

> 在这里，不需要函数体 {}。

看起来非常绕。
或许应该介绍说类似于 c++ 中的`using` ：定义了一种用户类型

**Comment by Unknwon** [comment]
额。。建议提个 PR。。嘿嘿

**Comment by lizebang** [comment]
@dongshimou 
我不是特别明白你的意思？
这和你所说的 c++ 中的 `using` 不一样。
在 go 中，`type binOp func(int, int) int` 只是定义了一个函数类型。带有两个 int 参数且返回一个 int 的函数是 binOp 类型。这里没有任何问题。

**Comment by dongshimou** [comment]
是我理解错了.
cpp中的 `using f1=xxx` 在go中是 `type f1=xxx`
