### ISSUE TITLE
7.6.4 修改字符串中的某个字符--代码运行报错

### ISSUE THREAD

**Issue by xsteadybcgo** [Unknwon/the-way-to-go_ZH_CN#425]
引号导致编译报错
`func main() {
	s := "hello"
	c := []byte(s)
	c[0] = ‘c’ //  单引号为英文状态下 'c'
	s2 := string(c) 
	fmt.Printf("%v", s2)
}`

**Comment by Unknwon** [comment]
额。。建议提个 PR。。嘿嘿
