### ISSUE TITLE
第 14 章有缺失？

### ISSUE THREAD

**Issue by l5oo00** [Unknwon/the-way-to-go_ZH_CN#430]
看到  14.9   结尾链接的下一节还有  14.10， 但是点击后  404

然后 15.0 结尾的上一节还有 14.17， 点击后也是 404

应该是缺失了？

**Comment by qichengzx** [comment]
应该是有些章节还没写，但是有计划，所以有些链接会404

**Comment by Unknwon** [comment]
是的。。
