### ISSUE TITLE
import本地包的路径问题

### ISSUE THREAD

**Issue by lonycc** [unknwon/the-way-to-go_ZH_CN#432]
在windows和mac上均测试过的结果，以examples的chapter_13, panic_package.go为例, 其中有导入 "./parse/parse",  执行go run panic_package.go, 会报错 cannot find package "./parse/parse", 然而将导入语句改成"./parse", 则可顺利执行。

备注：我本机设置了GOROOT和GOPATH环境变量, 而download下来的这些demo并非放在GOPATH目录下。

**Comment by Unknwon** [comment]
。。你在说神马？
