### ISSUE TITLE
9.7  "可执行文件 hg.a 将被放到 $GOPATH" 中的$GOPATH应改为$GOROOT

### ISSUE THREAD

**Issue by jgm-learn** [Unknwon/the-way-to-go_ZH_CN#441]
这是原文
Install with the command:  go install tideland-cgl.googlecode.com/hg
This puts the executable file hg.a in the map $GOROOT/pkg/linux_amd64/tideland-cgl.
googlecode.com, and puts the Go source-files in  $GOROOT/src/tideland-cgl.googlecode.com/
hg, and also hg.a in a submap _obj.

**Comment by Unknwon** [comment]
额。。建议提个 PR。。嘿嘿

**Comment by lizebang** [comment]
@jgm-learn 麻烦关一下 issue ...

**Comment by Unknwon** [comment]
@lizebang 这个修复了吗？没看到有 PR 链接到这个 issue 呢。

**Comment by lizebang** [comment]
@Unknwon #442
