### ISSUE TITLE
04.2.md 里面好几个 .go 写成了 .o ，建议改一下

### ISSUE THREAD

**Issue by bingo8670** [Unknwon/the-way-to-go_ZH_CN#477]
04.2.md 里面有三个个 .go 写成了 .o ，建议整体搜索一下，看看其他文件有没有这个问题；
![image](https://user-images.githubusercontent.com/26355174/40289505-5a64f4b0-5ceb-11e8-91a9-f15ebfc6452f.png)

好像也有点吹毛求疵了，不过这么做是为了社区更好的发展，见谅。

**Comment by Unknwon** [comment]
挺好的。。提个 PR 吧。。

**Comment by bingo8670** [comment]
已推
