### ISSUE TITLE
12.3例子：文件拷贝中的示例有bug

### ISSUE THREAD

**Issue by stevefoxuser** [Unknwon/the-way-to-go_ZH_CN#488]
io.Copy(dst, src)  执行了copy以后，如果dst文件已经存在，并且src的文件长度小于dst的文件，就会发生dst文件只有**部分**被覆盖的情况。
例如src文件内容是 123 ， dst文件内容是 abcd。 
执行完copy以后dst文件内容预期是：123，得到却是：123d。
只要打开dstName文件的时候把os.OpenFile改成os.Create即可修复这个问题

**Comment by Unknwon** [comment]
建议提个 PR

**Comment by stevefoxuser** [comment]
提了
