### ISSUE TITLE
14.2.1 语句不通

### ISSUE THREAD

**Issue by carlonelong** [Unknwon/the-way-to-go_ZH_CN#513]
“而Go有一个特殊的类型，通道（channel），像是通道（管道），可以通过它们发送类型化的数据在协程之间通信，可以避开所有内存共享导致的坑；通道的通信方式保证了同步性。数据通过通道：同一时间只有一个协程可以访问数据：所以不会出现数据竞争，设计如此。数据的归属（可以读写数据的能力）被传递。”

这段建议重新翻译

**Comment by Unknwon** [comment]
hi,建议直接提一个 PR~

**Comment by lynn9388** [comment]
> Instead Go has a special type, the channel, which is a like a conduit (pipe) through which you
> can send typed values and which takes care of communication between goroutines, avoiding
> all the pitfalls of shared memory; the very act of communication through a channel guarantees
> synchronization. Data are passed around on channels: only one goroutine has access to a data item at
> any given time: so data races cannot occur, by design. The ownership of the data (that is the ability to
> read and write it) is passed around. 
> http://files.cnblogs.com/files/rojas/thewaytogo.pdf

**Comment by lynn9388** [comment]
> Instead Go has a special type, the channel, which is a like a conduit (pipe) through which you can send typed values and which takes care of communication between goroutines, avoiding all the pitfalls of shared memory; the very act of communication through a channel guarantees synchronization. Data are passed around on channels: only one goroutine has access to a data item at any given time: so data races cannot occur, by design. The ownership of the data (that is the ability to read and write it) is passed around. 
>
> http://files.cnblogs.com/files/rojas/thewaytogo.pdf

而 Go 有一种特殊的类型，*通道（channel）*，就像一个可以用于发送类型化数据的管道，由其负责协程之间的通信，从而避开所有由共享内存导致的陷阱；这种通过通道进行通信的方式保证了同步性。数据在通道中进行传递：*在任何给定时间，一个数据被设计为只有一个协程可以对其访问，所以不会发生数据竞争。* 数据的所有权（可以读写数据的能力）也因此被传递。
