### ISSUE TITLE
第11章的exercise中的min_interface.go的Min函数并不能得到最小值

### ISSUE THREAD

**Issue by GravityConstant** [Unknwon/the-way-to-go_ZH_CN#536]
func main() {
	a := []int{99, 11, 33, 44, 22, 55, 77}
	min := vendor.Min(vendor.IntArray(a))
	fmt.Println(min) // 22
}
// 解决
func Min(data Miner) interface{} {
	j := 0
	for i := 1; i < data.Len(); i++ {
		if data.Less(i, j) {
			j = i
		}
	}
	return data.ElemIx(j)
}

**Comment by xinjiguaike** [comment]
I also find this issue

**Comment by GravityConstant** [comment]
作者已解决
