### ISSUE TITLE
13.4 自定义包中的错误处理和 panicking：程序运行的输出不对

### ISSUE THREAD

**Issue by xiaomdong** [Unknwon/the-way-to-go_ZH_CN#558]
文章中的输出为：
Parsing "1 2 3 4 5":
  [1 2 3 4 5]
Parsing "100 50 25 12.5 6.25":
  pkg parse: error parsing "12.5" as int
Parsing "2 + 2 = 4":
  pkg parse: error parsing "+" as int
Parsing "1st class":
  pkg parse: error parsing "1st" as int
Parsing "":
  pkg: no words to parse

实际代码的输出应该是：
Parsing "1 2 3 4 5":
  [1 2 3 4 5]
Parsing "100 50 25 12.5 6.25":
  pkg: pkg parse: error parsing "12.5" as int
Parsing "2 + 2 = 4":
  pkg: pkg parse: error parsing "+" as int
Parsing "1st class":
  pkg: pkg parse: error parsing "1st" as int
Parsing "":
  pkg: no words to parse

**Comment by Unknwon** [comment]
来个pr更佳

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xiaomdong** [comment]
om

**Comment by xiaomdong** [comment]
ok
