### ISSUE TITLE
4.5.2 向低精度类型转换超过取值范围貌似不会引发panic

### ISSUE THREAD

**Issue by Chocolatl** [Unknwon/the-way-to-go_ZH_CN#568]
[4.5.2 数字类型](https://github.com/Unknwon/the-way-to-go_ZH_CN/blob/master/eBook/04.5.md#452-%E6%95%B0%E5%AD%97%E7%B1%BB%E5%9E%8B)中：
> 不过如果你实际存的数字超出你要转换到的类型的取值范围的话，则会引发 panic（第 13.2 节）。

我尝试以下代码并没有引发panic，输出结果为`-1`（go版本为`1.11.4`）：
```go
func main() {
	var a int32 = 0XFFFFFF
	fmt.Println(int8(a))
}
```

**Comment by Unknwon** [comment]
感谢指正，这个可能在 go 的新版本中做了优化和改动，建议提个 PR 将这局~~划掉~~

**Comment by inkedawn** [comment]
确实。
最新的Language Specification里的Conversions between numeric types一节写道，
此种情况会进行截断，而非panic

> 1. When converting between integer types, if the value is a signed integer, it is sign extended to implicit infinite precision; otherwise it is zero extended. **It is then truncated to fit in the result type's size.** For example, if v := uint16(0x10F0), then uint32(int8(v)) == 0xFFFFFFF0. The conversion always yields a valid value; there is no indication of overflow.

https://golang.org/ref/spec#Conversions

**Comment by Chocolatl** [comment]
抱歉，我重新看了一遍上下文，发现这句话是针对这句话上面那个栗子的，是我太粗心了。感谢你们的解答
