### ISSUE TITLE
python&go

### ISSUE THREAD

**Issue by mn3711698** [Unknwon/the-way-to-go_ZH_CN#570]
在  1.1 起源与发展  这个章节的内容里，我看到   Go 语言的官方网站是 golang.org，这个站点采用 Python 作为前端，并且使用 Go 语言自带的工具 godoc 运行在 Google App Engine 上来作为 Web 服务器提供文本内容。    我想了解处，这个是怎么样的处理方式？因为我目前是python  web开发，想了解一下，用python与go怎么协同开发？

**Comment by Unknwon** [comment]
你好。。本书并不能回答你这个问题
