### ISSUE TITLE
README.md中给出的下载链接失效问题

### ISSUE THREAD

**Issue by 236212005** [Unknwon/the-way-to-go_ZH_CN#576]
- 问题页面：https://github.com/Unknwon/the-way-to-go_ZH_CN#%E5%BC%80%E5%A7%8B%E9%98%85%E8%AF%BB

- 问题章节：开始阅读

- 问题连接：下载本书:PDF（https://go.fdos.me/down/book.pdf），MOBI（https://go.fdos.me/down/book.mobi），EPUB（https://go.fdos.me/down/book.epub）

- 问题现象：“无法访问此网站，go.fdos.me 的响应时间过长。ERR_TIMED_OUT”

**Comment by cheenbee** [comment]
gitbook上可以[下载] (https://legacy.gitbook.com/book/tl3shi/the-way-to-go/details)

**Comment by Unknwon** [comment]
好的。。我直接删了链接

**Comment by 236212005** [comment]
> gitbook上可以[下载] (https://legacy.gitbook.com/book/tl3shi/the-way-to-go/details)

谢谢。

**Comment by 236212005** [comment]
> 好的。。我直接删了链接

风骚的操作，华丽的走位
