### ISSUE TITLE
练习 5.5 for_character.go 翻译建议

### ISSUE THREAD

**Issue by Respawnz** [Unknwon/the-way-to-go_ZH_CN#579]
use only one for loop and string concatenation
翻译为:使用一层 for 循环以及字符串截断。
建议`截断`改为`叠加`

**Comment by Respawnz** [comment]
或者说改成`连接` ,截断实在让人摸不着头脑

**Comment by LawsD** [comment]
这个翻译确实不对，是串联，连接的意思

**Comment by Unknwon** [comment]
你说的对！建议提交一个 PR，嘿嘿
