### ISSUE TITLE
4.5.2.1 格式化说明符%0d翻译问题

### ISSUE THREAD

**Issue by LawsD** [Unknwon/the-way-to-go_ZH_CN#591]
> %0d 用于规定输出定长的整数，其中开头的数字 0 是必须的。

该说明在原文中为

> %0nd shows an integer with n digits, and leading 0 is necessary.

翻译不准确，遗漏了中间的n的说明，看到这时一脸懵逼，去查了原文才看懂，建议改为

> %0nd 用于规定输出长度为n的整数，其中开头的0是必须的。

**Comment by Unknwon** [comment]
你说的对。。建议提个一个 pr！
