### ISSUE TITLE
9.5自定义包和可见性 

### ISSUE THREAD

**Issue by hkui** [Unknwon/the-way-to-go_ZH_CN#607]
import "./pack1/pack1"
引入对吗，运行根本找不到啊

**Comment by Unknwon** [comment]
你的提问太精简了，我也只能这样精简地回答一下你

**Comment by hkui** [comment]
import "./pack1/pack1"

**Comment by YWNA** [comment]
> import "./pack1/pack1"应该是 import "./pack1"吧

那你自己不也发现了猫腻嘛。具体怎么import就要看你的目录结构了。
![image](https://user-images.githubusercontent.com/9693232/56777766-c4f49800-6805-11e9-865b-ebaf41ba4173.png)

**Comment by hkui** [comment]
> 腻嘛。具体怎

嗯嗯
