### ISSUE TITLE
hello world案例就有错了

### ISSUE THREAD

**Issue by dk333** [Unknwon/the-way-to-go_ZH_CN#622]
package main

func main() {
	println("Hello", "world")
}
这是区分大小写的，Println

**Comment by aircjm** [comment]
## 我试了是可以编译通过。
![image](https://user-images.githubusercontent.com/18283183/57061825-f03d2280-6cf0-11e9-9366-69f157f766d9.png)

## 我查了下，这个是builtin 包下面的一个函数。应该是内置函数的一种
![image](https://user-images.githubusercontent.com/18283183/57061853-0b0f9700-6cf1-11e9-9e39-7e25a8d69acd.png)

## 你说的应该是fmt包下面的，
![image](https://user-images.githubusercontent.com/18283183/57061938-5164f600-6cf1-11e9-8d3a-92593fc8a9fa.png)

**实际上你这个才是错误的，Println方法，必须先import fmt包，并且通过fmt来调用**
