### ISSUE TITLE
18.4 结构体

### ISSUE THREAD

**Issue by ghostlo** [Unknwon/the-way-to-go_ZH_CN#638]
ms := Newstruct1{10, 15.5, "Chris"}

应为
ms := Newstruct1(10, 15.5, "Chris")

**Comment by sylartp** [comment]
@ghostlo 
没有问题吧 这本来就是字面量初始化结构体
你也可以 ms := new(Newstruct1)  然后通过选择器赋值

**Comment by ghostlo** [comment]
我的锅，抱歉
