### ISSUE TITLE
6.7 将函数作为参数IndexFunc参数类型错误

### ISSUE THREAD

**Issue by kimmosc2** [unknwon/the-way-to-go_ZH_CN#664]
原文:

> 该函数的签名是 func IndexFunc(s string, f func(c int) bool) int，它的返回值是在函数 f(c) 返回 true、-1 或从未返回时的索引值。

正确的应该是 func IndexFunc(s string, f func(rune) bool) int,虽然rune是int32的别名但还语法层面有区别的

**Comment by unknwon** [comment]
建议直接搞个 PR 喔~
