### ISSUE TITLE
14.17 使用通道并发访问对象这章有问题

### ISSUE THREAD

**Issue by Ricardo-lu** [unknwon/the-way-to-go_ZH_CN#718]
本章开头有句话：
>这个结构在构造函数NewPerson()中初始化的同时会启动一个后台协程backend()。backend()方法会在一个无限循环中执行chF中放置的所有函数，有效的将它们序列化从而提供了安全的并发访问。

看代码就是把 get 和 set 操作都通过 channel 到 backend 实现序列化，乍一看是没什么问题的，但是测试起来发现好像并没有什么用
```
func main() {
	bs := NewPerson("Smith Bill", 2500.5)
	fmt.Println(bs)
	for i := 0; i < 100; i++ {
		go func() {
			bs.SetSalary(bs.GetSalary()+1)
		}()
	}
	fmt.Println("Salary changed:")
	fmt.Println(bs)
}
```
输出
```
Person - name is: Smith Bill - salary is: 2500.50
Salary changed:
Person - name is: Smith Bill - salary is: 2511.50
```
实际上代码序列化 get 和 set 的操作并没有什么用，多并发的情况下，每个协程的 getValue 和 setValue 还是会混在一起，这只不过是把 CPU 上的多线程计算数据混乱的问题给搬到了代码层面上而已。
所以我不禁怀疑这章存在的意义是？？？？

**Comment by unknwon** [comment]
>实际上代码序列化 get 和 set 的操作并没有什么用，多并发的情况下，每个协程的 getValue 和 setValue 还是会混在一起

预期是什么？

**Comment by Ricardo-lu** [comment]
@unknwon 
>有效的将它们序列化从而提供了安全的并发访问

安全的并发访问应该就是循环多少次加多少吧，就像这样
```
for i := 0; i < 100; i++ {
	go func() {
		bs.SetSalary(bs.GetSalary()+1)
	}()
}
```
预期的结果
```
Person - name is: Smith Bill - salary is: 2500.50
Salary changed:
Person - name is: Smith Bill - salary is: 2600.50
```
backend 函数虽然的确把请求都序列化了，但是好像并没有什么用处

**Comment by unknwon** [comment]
你的代码并没有阻止程序退出啊，剩下的goroutine被执行完就被释放了。

你需要自己做同步控制：https://play.golang.org/p/6LC0BcNUarj

**Comment by Ricardo-lu** [comment]
@unknwon 
我没太明白你的意思，阻止程序退出好像和运算没什么关系。goroutine 执行完不释放还需要做什么呢

我参照 SetSalary() 写出了这样的代码可达到我的预期
```
func (p *Person) change(fun func())  {
	p.chF <- fun
}
func main() {
	bs := NewPerson("Smith Bill", 2500.5)
	for i := 0; i < 100; i++ {
		go func() {
			bs.change(func() {
				bs.salary +=1
			})
		}()
	}
}
```

**Comment by unknwon** [comment]
你之前的代码，goroutine并没有执行完。你有一百个，退出的时候才执行了十几个。

**Comment by Ricardo-lu** [comment]
@unknwon 执行了的，运行如下代码
```
func main() {
	bs := NewPerson("Smith Bill", 2500.5)
	fmt.Println(bs)
	for i := 0; i < 100; i++ {
		go func() {
			bs.SetSalary(bs.GetSalary()+1)
		}()
	}
	fmt.Println("Salary changed:")
	time.Sleep(2*1e9)
	fmt.Println(bs)
}
```
结果还是
```
Person - name is: Smith Bill - salary is: 2500.50
Salary changed:
Person - name is: Smith Bill - salary is: 2534.50
```
因为每个 goroutine 都会运行一个 GetSal 和 SetSal，多个 goroutine 运行的时候会顺序就混乱了
就像 AB 两个 goroutine，执行顺序可能会是这样的
- A 运行到 GetSal
- B 也运行到了 GetSal
- A SetSal 
- B SetSal
文章中的写法，B 的 GetSal 是可以插入到 A 的 Get 和 Set的，这样就是将多线程的错误从 CPU 层面移到了代码层面

**Comment by unknwon** [comment]
>你需要自己做同步控制：play.golang.org/p/6LC0BcNUarj

sleep 只是挂起线程，没有任何保证 goroutine 会全部执行

**Comment by unknwon** [comment]
ah，我看懂你的意思了。

作者的本意是提供一种编程模型进行序列化操作，并且示例代码中的 `SetSalary` 给的是一个绝对值，不包含加减这种相对操作。你给出的代码已经换需求了，所以需要修改具体实现。比如把 `SetSalary` 改成 `func IncreaseSalary(n int)`，关键值的修改应该是同步的。

**Comment by Ricardo-lu** [comment]
好吧，那如果作者的本意是这样的话那就没什么问题了，我也学到了 sync 的用法，谢谢解答
