### ISSUE TITLE
一个例子的小错误

### ISSUE THREAD

**Issue by tmacy89120** [Unknwon/the-way-to-go_ZH_CN#72]
the-way-to-go_ZH_CN/eBook/exercises/chapter_6/error_returnval.go

这个例子中，只用到了MySqrt1函数，而没有使用MySqrt2函数。

    Sqrt21, Err21 := MySqrt1(a)
    Sqrt22, Err22 := MySqrt1(b)

上述这两行应该是使用MySqrt2函数吧

**Comment by Unknwon** [comment]
看起来是的！多谢指正！
