### ISSUE TITLE
11.14章节的func (cs Cars) Map有什么作用

### ISSUE THREAD

**Issue by oule55555** [unknwon/the-way-to-go_ZH_CN#737]
测试删除了这个方法程序也能运行,为什么还要特别写出func (cs Cars) Map这个方法呢

**Comment by unknwon** [comment]
![Screen Shot 2019-11-17 at 7 26 04 PM](https://user-images.githubusercontent.com/2946214/69022416-1b771e80-0970-11ea-8ee6-7236dd13feab.png)

应该是正文要求吧。。
