### ISSUE TITLE
chapter_19/goto_v1/main.go的 add方法 form表单content-type不对

### ISSUE THREAD

**Issue by yifeng01** [unknwon/the-way-to-go_ZH_CN#738]
https://github.com/unknwon/the-way-to-go_ZH_CN/blob/master/eBook/examples/chapter_19/goto_v1/main.go
36行前添加  
w.Header().Set("Content-Type", "text/html")

否则浏览器显示源字符串 （错误内容类型：“text/plain”）

go版本 go version go1.12.6 darwin/amd64

**Comment by unknwon** [comment]
建议直接提个 PR~
