### ISSUE TITLE
https://github.com/unknwon/the-way-to-go_ZH_CN/blob/master/eBook/examples/chapter_19/goto_v5/store.go rpc的导出方法参数不对

### ISSUE THREAD

**Issue by yifeng01** [unknwon/the-way-to-go_ZH_CN#739]
https://github.com/unknwon/the-way-to-go_ZH_CN/blob/master/eBook/examples/chapter_19/goto_v5/store.go  的67行  Count方法改为小写开头的count，即不导出， 否则rpc注册时 rpc导出方法参数不对。 同样75行也改为小写count调用。

**Comment by unknwon** [comment]
建议直接提个 PR~
