### ISSUE TITLE
15.9 节应该是有bug,

### ISSUE THREAD

**Issue by SealinGp** [unknwon/the-way-to-go_ZH_CN#745]
本机环境
系统:ubuntu 16.04 LTS
go version go1.12.8 linux/amd64

问题描述:
rpc服务端可以正常监听
rpc客户端可以正常拨号,无法正常调用,一直堵塞在调用返回的结果

具体代码以及执行命令:
rpc.go:
```go
package main

import (
	"fmt"
	"net"
	"net/http"
	"net/rpc"
	"os"
)

/*
https://github.com/unknwon/the-way-to-go_ZH_CN/blob/master/eBook/15.9.md
适用于两服务端均为 基于go 的 RPCs服务 之间的数据传输
基于 gob.go里面的 gob 包
用于在两台不同的服务器之间go服务的调用
*/
func init() {
	fmt.Println("Content-Type:text/plain;charset=utf-8\n\n")
}
func main() {
	args := os.Args
	if len(args) <= 1 {
		fmt.Println("lack param ?func=xxx")
		return
	}

	execute(args[1])
}
func execute(n string) {
	funs := map[string]func(){
		"rpc1" : rpc1,
		"rpc2" : rpc2,
		"rpc3" : rpc3,
	}
	if nil == funs[n] {
		fmt.Println("func",n,"unregistered")
		return
	}
	funs[n]()
}

//server
func rpc1()  {
	/mt.Println("rpc server listening in: localhost:1234")
	go http.Serve(lis,nil)

	select {}
}
type Args struct {
	N,M int
}
func (*Args)Multiply(a Args,reply *int) error {
	*reply = a.M * a.N
	return nil
}

//client
func rpc2()  {
	//connect
	client,err := rpc.Dial("tcp","localhost:1234")
	if err != nil {
		fmt.Println("dial rpc server(localhost:1234) failed:"+err.Error())
		return
	}
	fmt.Println("connect success! start to call")

	//call
	defer client.Close()
	arg     := Args{2,3}
	reply   := 0
	err     = client.Call("Arg.Multiply",arg,&reply);
	if err != nil {
		fmt.Println("cal error:"+err.Error())
		return
	}
	fmt.Println("call success,ready to print result")

	fmt.Println(reply)
}

func rpc3()  {
	a := &Args{2,3}
	r := 0
	a.Multiply(*a,&r)
	fmt.Println(r)
}
```
服务端执行: go run rpc.go rpc1
客户端执行: go run rpc.go rpc2

**Comment by unknwon** [comment]
>rpc客户端可以正常拨号,无法正常调用,一直堵塞在调用返回的结果

Hmm，这个描述能不能更加清晰一点？（具体到调用了什么方法，预期是什么，结果是什么）

**Comment by SealinGp** [comment]
@unknwon 
如描述所说:
1.调用了rpc1方法(=执行: go run rpc.go rpc1) 作为服务端
2.调用了rpc2方法(=行: go run rpc.go rpc2)  作为客户端
客户端预期结果:
connect success! start to call
call success,ready to print result
6
客户端实际结果(一直卡在这里在,等了很久[预测超过5分钟]均无结果):
connect success! start to call

**Comment by unknwon** [comment]
Hmm，你贴出来的 rpc.go 的 rpc1 好像和 https://github.com/unknwon/the-way-to-go_ZH_CN/blob/master/eBook/examples/chapter_15/rpc/rpc_server.go 里的服务端代码，有所不同啊？

**Comment by SealinGp** [comment]
@unknwon  你说的不同是指 我的(rpc1) select {}  你链接所示的代码:time.Sleep(1000e9) ?这个地方?

**Comment by unknwon** [comment]
这个书里其实有不少反最佳实践，我建议看一下 http.Serve 这个调用是不是有错误返回

**Comment by unknwon** [comment]
我查了一下，可能是书里的内容过时了：
![Screen Shot 2019-12-11 at 10 34 54 PM](https://user-images.githubusercontent.com/2946214/70680504-7f86bd00-1c66-11ea-872e-d686ab8eba17.png)
https://golang.org/pkg/net/rpc/

**Comment by SealinGp** [comment]
@unknwon  你好,确实是的,使用rpc.DialHttp是成功输出预期结果的,感谢,然后 http.Serve 这个没有 错误放回

**Comment by unknwon** [comment]
我发现示例代码的确用的 `rpc.DialHTTP`...

https://github.com/unknwon/the-way-to-go_ZH_CN/blob/c308fad89f948f84f240cbf6428d72acca232308/eBook/examples/chapter_15/rpc/rpc_client.go#L21
