### ISSUE TITLE
是不是每小节给个标题比较好？

### ISSUE THREAD

**Issue by shadyxu** [Unknwon/the-way-to-go_ZH_CN#98]
光看1.1.md不知道啥意思啊，还得点进去看。

**Comment by Unknwon** [comment]
明明有目录。。。

**Comment by shadyxu** [comment]
我知道有目录，也看到了。但是有些人可能直接点到files里面浏览，获取下下来离线看，就不太方便了。

**Comment by Unknwon** [comment]
给md命名完也不见得就能看懂。。。:sweat:

**Comment by shadyxu** [comment]
小节名复制到文件名肯定能懂呀。就是提个建议，不同意就忽略吧。
